const QUESTION_BANK_TEEN = {
    0: [ // Stage 0: Logical / Worded Math
        "If a train travels 60 kilometers in one hour, how many minutes will it take to travel 15 kilometers?",
        "You have a 5-liter jug and a 3-liter jug, and an unlimited supply of water. How do you measure exactly 4 liters?",
        "If five cats can catch five mice in five minutes, how long will it take one cat to catch one mouse?",
        "A bat and a ball cost 110 rupees in total. The bat costs 100 rupees more than the ball. How much does the ball cost?",
        "If you are running in a race and you overtake the person in second place, what place are you in now?",
        "What comes next in the sequence: 2, 6, 12, 20, 30...?",
        "A farmer has 17 sheep and all but 9 run away. How many are left?",
        "Divide 30 by half and add 10. What is the answer?",
        "If two typists can type two pages in two minutes, how many typists will it take to type 18 pages in six minutes?",
        "A snail is at the bottom of a 20-foot well. Each day, it climbs up 5 feet, but at night, it slips back 4 feet. How many days will it take for the snail to reach the top?",
		"If you buy a notebook for 45 rupees and sell it for 60, but then buy it back for 70 and sell it for 80, how much total profit did you make?",
        "A clock shows exactly 3:15. What is the angle between the hour and the minute hands?",
        "You are in a race. You pass the person in second place. What place are you in now?",
        "An apple and a banana together cost 150 rupees. The apple costs 100 rupees more than the banana. How much does the banana cost?",
		"If 3 days ago was the day before Friday, what day will it be tomorrow?",
        "You have 3 doors to escape through. Behind door 1 is a massive fire. Behind door 2 is an armed assassin. Behind door 3 is a lion that hasn't eaten in 3 years. Which door is the safest?",
        "A merchant can place 8 large boxes or 10 small boxes into a carton. In one shipment, he sent a total of 96 boxes. If there are more large boxes than small boxes, how many cartons did he ship?",
        "How many times can you subtract the number 10 from 100?",
        "If a basket of apples doubles every minute, and it takes exactly 60 minutes to fill the basket completely, how many minutes did it take for the basket to be half full?",
		"If it takes 5 machines exactly 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?",
        "A father and son are in a horrible car crash. The father dies. The son is rushed to the hospital. In the operating room, the surgeon looks at the boy and says, 'I can't operate on him. He is my son.' How is this possible?",
        "You are running a massive marathon with 500 people. Just before the finish line, you overtake the person in 499th place. What is your position now?",
        "A red house is made of red bricks, and a blue house is made of blue bricks. What is a greenhouse made of?",
        "I have branches, but I have no fruit, no trunk, and no leaves. What am I?",
        "If it takes 8 workers 10 hours to build a wall, how long would it take 4 workers to build the exact same wall?",
		"You have a match, a candle, a gas stove, and a fireplace. Which do you light first?",
        "Divide 40 by half and add 20. What is the exact result?",
        "An electric train is moving east at 80 mph, and the wind is blowing west at 20 mph. Which way does the smoke blow?",
        "If it takes 3 nurses 3 minutes to measure the blood pressure of 3 patients, how long will it take 100 nurses to measure 100 patients?",
        "What mathematical symbol can you put between 5 and 9 to get a number bigger than 5 but smaller than 9?",
        "A plane crashes exactly on the border of India and Nepal. Where do they legally bury the survivors?",
        "How many months of the year have 28 days?",
        "If there are 6 apples in a bowl and you take away 4, how many do you have?",
        "A boy is 4 years old, and his sister is half his age. When the boy is 100, how old is his sister?",
        "You walk into a dark room with a rabbit holding a carrot, a pig eating slop, and a chimp holding a banana. Which animal is the smartest?",
		"If a doctor gives you 3 pills and tells you to take one every half hour, how long will they last?",
        "How many times does the digit '9' appear in the numbers from 1 to 100?",
        "If you drop a 10-kg iron ball and a 1-kg cotton ball from the same height in a vacuum, which hits the ground first?",
        "A father is currently 3 times as old as his son. In 12 years, he will be twice as old. How old is the son now?",
        "What comes next: O, T, T, F, F, S, S, E, N...?",
        "If 5 peacocks lay 10 eggs in 2 days, how many eggs will 1 peacock lay in 4 days?",
        "A man builds a house with 4 sides. Every side faces south. A bear walks past. What color is the bear?",
        "You have a 10x10x10 solid cube made of smaller 1x1x1 cubes. If you paint the outside red, how many small cubes have exactly zero red faces?",
        "If it is 7:00 AM now, what time will it be 2400 hours from now?",
        "How can you make the equation 8 + 8 = 4 true without changing the numbers?",
        "A farmer has 20 cows. All but 11 die. How many are left?",
        "Mary's father has 5 daughters: Nana, Nene, Nini, Nono. What is the 5th daughter's name?",
        "Some months have 30 days, some have 31. How many have 28?",
        "If you divide 100 by zero, what is the mathematical result?",
        "A monkey is climbing a 30-foot pole. He climbs 3 feet up and slides 2 feet down every minute. How long to reach the top?",
        "What is the next prime number after 31?",
        "If x + y = 10 and x - y = 4, what is the value of x times y?",
        "You are facing North. You turn 90 degrees right, 180 degrees left, and 270 degrees right. Which way are you facing now?",
        "Which is heavier: a ton of bricks or a ton of feathers?",
        "If a completely blind person asks you how many fingers they are holding up, how do you mathematically figure it out?"
    ],
    1: [ // Stage 1: Yes/No or True/False
        "True or False: Rules are meant to be broken as long as no one gets physically hurt.",
        "Yes or No: Do you believe marks are the only true measure of intelligence?",
        "True or False: It is better to be the leader of a failing project than a follower in a successful one.",
        "Yes or No: If your best friend cheats in an exam, would you tell the teacher?",
        "True or False: Hard work always beats talent.",
        "Yes or No: Do you often feel that your teachers do not understand you?",
        "True or False: Winning is more important than participating.",
        "Yes or No: Are you comfortable speaking in front of the entire school assembly?",
        "True or False: Logic is more important than emotions when making a decision.",
		"True or False: It is completely okay to lie to your parents if it saves them from unnecessary stress.",
        "Yes or No: Would you skip your own birthday party to study for a crucial entrance exam?",
        "True or False: You learn much more from failing terribly than from succeeding easily.",
        "Yes or No: Do you often compare your real life to the fake lives people post on Instagram?",
        "True or False: Playing strategic video games teaches better real-world problem-solving skills than reading school textbooks.",
		"True or False: Your self-worth is deeply tied to how many likes or views you get on social media.",
        "Yes or No: Is it better to choose a safe, high-paying career you hate rather than a risky career you love?",
        "True or False: You often pretend to agree with your friends just to avoid an argument.",
        "Yes or No: Do you believe that the school system rewards obedience more than actual creativity?",
        "True or False: A person who fails exams but has good street smarts will eventually be more successful than a class topper with no social skills.",
		"True or False: Cheating in an exam is only morally wrong if you get caught.",
        "Yes or No: Would you permanently sacrifice your own happiness to fulfill your parents' unfulfilled career dreams?",
        "True or False: People who are poor just don't work hard enough.",
        "Yes or No: Is it acceptable to severely bully a bully in order to teach them a lesson?",
        "True or False: The academic grades you get right now will completely define how successful you are in your 30s.",
        "Yes or No: Do you give up easily when a math problem is too hard?",
		"Yes or No: Do you believe your teachers treat the 'toppers' differently than average students?",
        "True or False: It is impossible to become a billionaire without exploiting other people.",
        "Yes or No: Would you report your absolute favorite teacher if you caught them taking a bribe?",
        "True or False: Boys and girls face the exact same academic and social pressures in Indian society.",
        "Yes or No: Is it fair that major entrance exams focus heavily on rote memorization rather than creative problem solving?",
        "True or False: A student who secures 99% is automatically a better human being than a student who secures 50%.",
        "Yes or No: If given a fully-funded chance, would you permanently move out of India for better career opportunities?",
        "True or False: Your parents' financial status should dictate what career you are allowed to choose.",
        "Yes or No: Is it okay to make a culturally insensitive joke if it is 'just a meme' among your close friends?",
        "True or False: Respecting elders means never arguing with them, even when they are completely factually incorrect.",
		"True or False: If you find a wallet with 10,000 rupees and no ID, keeping it is completely acceptable.",
        "Yes or No: Do you believe that your generation is significantly smarter than your parents' generation?",
        "True or False: A student who bullies others is usually a victim of bullying themselves.",
        "Yes or No: Would you take a pill that instantly makes you a genius but shortens your life by 10 years?",
        "True or False: People only volunteer for charity to make themselves look good.",
        "Yes or No: Is it okay to break a traffic rule if the road is completely empty at 2 AM?",
        "True or False: School uniforms successfully hide the financial inequality between students.",
        "Yes or No: Do you think AI will eventually take away your dream job?",
        "True or False: Strict parents raise the best liars.",
        "Yes or No: If your school was burning down, would you risk your life to save your exam records?",
        "True or False: Money cannot buy happiness, but poverty guarantees sadness.",
        "Yes or No: Would you secretly read your best friend's diary if you knew they would never find out?",
        "True or False: Most teachers prefer the quiet, obedient students over the smart, questioning ones.",
        "Yes or No: Do you believe karma actually exists in the real world?",
        "True or False: Extracurricular activities are just a distraction from real studying.",
        "Yes or No: Is it fair that the school captain gets away with minor rule-breaking?",
        "True or False: You learn more from YouTube tutorials than from your school textbooks.",
        "Yes or No: Would you ever sacrifice an animal to save a human?",
        "True or False: Taking revenge is sometimes the only way to get true justice.",
        "Yes or No: Do you think the current voting age of 18 should be lowered to 16?"
    ],
    2: [ // Stage 2: One Sentence Answers
        "Describe your biggest academic weakness in exactly one sentence.",
        "If you had to choose between being respected or being liked, which one do you pick and why?",
        "In one sentence, what do you do when you are completely overwhelmed with homework?",
        "What is the most unfair rule in your school?",
        "If someone insults you publicly, what is your immediate reaction?",
        "Describe what success looks like to you in a single sentence.",
        "How do you handle working with a classmate you strongly dislike?",
        "What is your strategy when you have two exams on the same day?",
        "In one sentence, why do you think students get addicted to social media?",
		"In one sentence, how do you react when you get a much lower grade than you expected?",
        "What do you do when you are assigned a school project with a team leader who has no idea what they are doing?",
        "Describe your ideal study environment in exactly one sentence.",
        "In a single sentence, what is the most effective way to handle a bully who won't leave you alone?",
        "What is your immediate thought when an adult heavily criticizes your hard work?",
		"In one sentence, how do you handle a situation where your parents compare you to a highly successful cousin?",
        "What is the very first thing you do when you realize you have lost your smartphone?",
        "Describe your reaction in one sentence if your best friend suddenly stops talking to you without any explanation.",
        "If you could instantly change one thing about the Indian education system, what would it be?",
        "In a single sentence, what is the biggest lie teenagers tell their parents today?",
		"Describe the exact feeling you get when a teacher praises a student who you know copied the entire assignment.",
        "What is your immediate reaction when an adult tells you that your dream career has 'no scope' in India?",
        "In one sentence, why do you think teenagers care so much about branded clothes and expensive shoes?",
        "If you could completely ban one subject from your school syllabus today, what would it be and why?",
        "In exactly one sentence, how do you defend yourself when you are accused of something you didn't do?",
        "What do you do when you know you are right, but an adult tells you you are wrong?",
		"In exactly one sentence, what is the biggest source of anxiety in your daily life?",
        "Describe how you handle the pressure of studying a subject you completely despise.",
        "If you had to describe the Indian education system in one word, what would it be and why?",
        "What is your immediate thought when a friend scores higher than you after claiming they didn't study at all?",
        "In one sentence, define what a 'waste of time' means to you.",
        "How do you respond when your parents say 'In our days, we had it much harder'?",
        "Describe the feeling of seeing a classmate get punished for something you actually did.",
        "What is the single most important real-life skill that school completely fails to teach you?",
        "In one sentence, how do you deal with the fear of disappointing your parents?",
        "What is your immediate reaction when a relative gives you unsolicited advice about your future?",
		"In one sentence, describe the worst physical pain you have ever felt.",
        "What is your immediate reaction when you see a stray dog being mistreated on the street?",
        "Describe your most irrational fear in exactly one sentence.",
        "What is the first thing you would do if you woke up tomorrow and you were the Principal of your school?",
        "In one sentence, why do so many students hate studying Mathematics?",
        "How do you comfort a friend who is crying uncontrollably over a failed exam?",
        "Describe the exact feeling of knowing you are unprepared for an exam that starts in 5 minutes.",
        "In a single sentence, what is the best piece of advice you have ever ignored?",
        "What do you do when a teacher asks a question, you know the answer, but you are too shy to speak up?",
        "Describe your relationship with your siblings in one honest sentence.",
        "How do you react when you lose a game you were absolutely certain you would win?",
        "What is the most annoying habit your parents have when you are trying to study?",
        "In one sentence, define what makes a person 'successful'.",
        "What goes through your mind when you see someone cheating in an exam and getting away with it?",
        "Describe the taste of your favorite food using only one sentence.",
        "How do you handle a situation where you forget someone's name right after they introduce themselves?",
        "What is your immediate thought when the power goes out at night while you are studying?",
        "In one sentence, why do you think bullying happens in schools?",
        "Describe the feeling of finishing your absolute last exam of the year.",
        "What do you do when you are stuck in a conversation you desperately want to leave?"
    ],
    3: [ // Stage 3: 2-3 Sentences (Frustrating Scenarios)
        "Your teacher publicly scolds and punishes you for a mistake that your friend actually made, but your friend stays silent. How exactly do you handle this situation in the classroom?",
        "You worked on a science project for a month, but your partner, who did nothing, takes all the credit in front of the principal. Explain your next steps.",
        "Your parents are forcing you to take Science (PCM), but your true passion and talent lie in Arts and Design. How do you convince them, knowing they are very stubborn?",
        "You studied extremely hard for an exam, but you still failed because the questions were completely out of syllabus. The school refuses to change the grades. What is your reaction?",
        "You discover that the school captain, who is loved by everyone, has been stealing funds from the sports committee. Do you expose them and risk becoming the most hated person in school?",
        "A group of seniors is continuously bullying your younger sibling. If you report it, it might get worse. If you fight them, you will be suspended. What is your calculated move?",
        "You are given a group assignment, and your group members refuse to do any work, leaving it all to you. The deadline is tomorrow. What do you do?",
        "You find a copy of tomorrow's final exam paper on the floor. If you look at it, you will top the class. If you return it, the exam might get cancelled. What is your choice?",
        "Your sports coach drops you from the final match despite you being the best player, favoring someone who has rich parents. How do you process this injustice?",
		"Your parents have saved money for years to send you to a specific, expensive coaching institute. After a month, you realize the teaching style is terrible and you are learning nothing. How do you break this news to them?",
        "You accidentally break an expensive piece of science lab equipment. No one saw you. If you confess, your parents must pay a massive fine. If you stay quiet, the whole class loses their lab privileges. What is your calculated move?",
        "Your friends are planning to mass-bunk school to watch a highly anticipated movie. You know there is a surprise test that day which counts towards your final grade. Do you warn them and risk being called a traitor, or go with them?",
        "You are passionate about a niche career, like wildlife photography or game design, but your relatives constantly mock it at family gatherings, calling it a 'hobby for rich kids.' How do you defend your choice without being disrespectful?",
        "You are caught in a dilemma: you have a final exam tomorrow, but your younger sibling is having a severe panic attack and your parents are not answering their phones. What is your absolute priority?",
        "You discover a flaw in the school's online grading system that allows you to secretly change marks. Many of your friends are begging you to help them pass. Do you do it, report it to the principal, or just ignore it?",
        "You are participating in a state-level debate competition. Five minutes before your turn, you realize your core argument is factually incorrect. Do you confidently present the wrong facts, or risk fumbling by changing your speech on the spot?",
        "Your parents restrict your internet usage to one hour a day, arguing it ruins your focus. However, you need it for learning coding and reading educational blogs. How do you negotiate this without causing a massive fight?",
        "You are chosen as the class monitor. The most popular group in class threatens to socially boycott you if you report them for skipping class. Do you enforce the rules or turn a blind eye to keep your social status?",
        "A teacher openly mocks a student in your class for their physical appearance, and everyone laughs out of fear. You know it is completely wrong. What do you actually do in that exact moment?",
		"You have a brilliant idea for a school event, but the principal rejects it immediately without listening, calling it 'childish'. Do you give up or fight for it?",
		"You find out your absolute best friend has been spreading nasty rumors about you just to fit in with the 'cool' kids. Do you confront them privately, expose them publicly, or quietly cut them off? Explain your logic.",
        "You are selected to represent your school in a national science fair, but the school refuses to fund the travel expenses, and your parents cannot afford it. The principal says it's 'your problem.' What is your next move?",
        "You accidentally see your favorite, most respected teacher taking a bribe to leak an exam paper to a wealthy student. If you report it, the teacher loses their job and goes to jail. What do you do?",
        "A classmate who is physically much weaker than you constantly taunts and provokes you, knowing you will get suspended if you hit them. How do you permanently stop this harassment without using violence?",
        "Your parents read your personal diary and private chats without your permission and confront you about a harmless secret. Do you apologize to keep the peace, or do you fight back for your right to privacy?",
		"A poor student in your class is caught stealing food from another student's bag because they were genuinely hungry. The teacher is about to suspend them. Do you intervene? If so, what do you say?",
        "You are a project group leader. One team member is dealing with severe family issues and hasn't contributed. If you report them, they fail. If you don't, your overall grade suffers. What do you do?",
        "You witness a group of popular students making a fake social media profile to bully a quiet classmate. Confronting them will make you their next target. What is your calculated plan?",
        "Your school introduces a strict new policy that erases all personal expression and freedom. Most students hate it but are too scared to speak up. How do you organize a protest without getting expelled?",
        "You accidentally overhear two teachers discussing the upcoming exam questions. You now have a massive, unfair advantage. What do you actually do with this information?",
        "A close friend tells you a very dark secret and begs you not to tell anyone, but keeping the secret puts them in severe physical danger. Do you betray their trust to save them?",
        "You are offered a scholarship to a prestigious program. You know the runner-up comes from deep poverty and this is their only chance, while your parents can easily afford the fee. Do you step down?",
        "You realize your parents have deeply prejudiced views about a certain religion or caste. Do you actively challenge their worldview, or stay silent to maintain peace at home?",
        "During an online class, someone anonymously posts highly inappropriate content. The teacher mistakenly blames you. How do you clear your name without acting like a panicked victim?",
        "You have a brilliant business idea that could make you a millionaire by age 20, but it requires dropping out of 10th grade. How do you pitch this crazy idea to your traditional Indian parents?",
		"You accidentally scratch your neighbor's expensive car with your bicycle. No one saw you. If you tell them, your parents will be furious. What do you do?",
        "A new student joins your class. They have a severe stutter and everyone avoids them. You want to be their friend, but doing so might make you unpopular. What is your choice?",
        "You are writing a difficult exam and you notice the invigilator has fallen asleep. The topper's answer sheet is visible right next to you. Do you look?",
        "Your parents have forbidden you from going to a late-night party, but your friends have arranged a secret way for you to sneak out. Do you go? Why or why not?",
        "You discover a bag containing 50,000 rupees near a temple. There's a hospital bill inside with a poor person's name on it. How do you ensure the money reaches them safely?",
        "Your sibling borrows your favorite item without asking and completely destroys it. They beg you not to tell your parents because they will get beaten. How do you handle it?",
        "You are selected for a prestigious debate team, but your partner is someone you strongly dislike and who never does any work. How do you ensure you both win?",
        "You witness an older student selling drugs near the school gate. If you report it, they might harm you physically. What is your calculated response?",
        "Your school is hosting a talent show. You have practiced for months, but on the day of the show, your voice gives out. Do you still go on stage or back out?",
        "You find out your parents are secretly reading all your WhatsApp messages. Do you confront them in anger, or do you start feeding them fake information?",
        "A teacher gives you full marks on a question you know you answered incorrectly. The extra marks will push you to first rank. Do you correct the teacher?",
        "You are caught in a massive traffic jam and will miss your final exam if you stay in the bus. Walking means crossing a dangerous, busy highway. What do you do?",
        "Your group of friends suddenly starts ignoring you and hanging out without you. You don't know why. How do you handle this sudden isolation?",
        "You are given 10,000 rupees to organize a school farewell party. How do you allocate the budget to make sure everyone is happy without running out of money?",
        "You notice a classmate with unexplained bruises on their arms. They say they 'fell,' but you suspect abuse at home. What is your responsibility here?",
        "Your internet goes down 10 minutes before an online submission deadline. You have no mobile data left. Panic sets in. What is your immediate action plan?",
        "You are falsely accused of stealing a teacher's phone. All the circumstantial evidence points to you, but you are innocent. How do you prove it?",
        "You have to choose between saving your drowning pet dog or saving a drowning stranger who is a known criminal. Who do you save and why?",
        "Your parents are arguing fiercely and talking about divorce. You are in the next room listening. Do you intervene, or let them handle their adult problems?",
        "You are offered a free trip to space, but there is a 50% chance the rocket will explode. Do you take the risk for the adventure of a lifetime?"
    ],
    4: [ // Stage 4: Stress Test (Deep, Under the Skin Opinions)
        "Many adults believe that your generation is entirely addicted to screens, lazy, and lacks real-world survival skills. Defend your generation, or admit they are completely right.",
        "A student who studies half as much as you gets higher marks simply because they rote-memorized the textbook, while you tried to understand the concepts. Is the Indian education system completely broken, or are you just making excuses for not studying the right way?",
        "Social media influencers make millions doing silly dances, while scientists and teachers struggle to pay bills. Does hard work and education actually matter anymore, or is life just about getting famous?",
        "If money was not a problem, what would you actually do with your life? And why aren't you brave enough to pursue that right now?",
        "Reservation and quota systems in Indian colleges mean that someone with fewer marks than you might get your seat. Do you think this is fair for social equality, or is it a punishment for merit?",
        "AI like me can now write essays, solve complex math, and code faster than any human. Doesn't that make your current school education completely useless?",
        "Parents often compare their children to 'Sharma ji ka beta' (the overachiever). Does this comparison motivate you to do better, or does it just build deep resentment?",
        "You are forced to respect elders in India purely based on their age, even if they are wrong or toxic. Do you agree with this cultural norm, or do you believe respect must be earned?",
        "Some students use depression and anxiety as an excuse to escape hard work and exams. How do you tell the difference between someone who is genuinely struggling and someone who is just lazy?",
        "Schools ruthlessly punish students for using AI like ChatGPT, yet every adult uses it to do their jobs faster. Is the education system hypocritical, or are you just trying to find shortcuts to avoid real learning?",
        "The 'hustle culture' tells you to sleep less and study more if you want to crack JEE or NEET. Are you willing to sacrifice your mental health and teenage years just for a college seat, or is that toxic brainwashing?",
        "Many parents view their children as retirement plans. They invest heavily in your education so you can take care of them later. Is this an unfair financial burden on you, or is it your absolute duty as an Indian child?",
        "You claim to have strong moral values, but if a dark-web source offered you the leaked paper for an exam that determines your entire career, are you absolutely certain you wouldn't take a peek? Be brutally honest.",
        "It is impossible to be highly successful, deeply ethical, and completely stress-free all at the same time in today's world. Which one of those three are you willing to sacrifice right now for your career?",
		"Society tells you to 'follow your passion', but when your passion doesn't pay the bills, society calls you a failure. Are you mentally prepared to be poor but happy, or will you eventually surrender to the corporate rat race like everyone else?",
        "We constantly blame politicians and the older generation for corruption, but teenagers cheat in exams, pirate movies, and lie to their parents daily. Isn't your generation just as corrupt, just on a smaller scale?",
        "Many students complain about mental health issues because of academic pressure. Is it possible that the pressure isn't actually that high, and your generation has just lost the mental toughness to handle hard work?",
        "You demand privacy and independence from your parents, yet you are completely dependent on them for money, food, and shelter. Don't they have the absolute right to control your life until you earn your own living?",
        "Imagine you work extremely hard and get a 95%, but your parents just ask, 'Where did the other 5% go?' Does this make you want to work harder to prove them wrong, or completely give up because nothing is ever enough?",
		"Look at the world right now—climate change, wars, economic crashes. As a teenager, do you feel hopeful about your future, or do you feel like the older generations have ruined the planet for you?",
		"You claim you want to be highly successful, but look at your daily screen time. Aren't you just lying to yourself and wasting the most crucial years of your life on cheap digital entertainment?",
        "Many teenagers say they want to 'change the world', yet they can't even keep their own bedrooms clean or wake up on time without their mothers yelling at them. Why should anyone take your generation's ambitions seriously?",
        "Think about the student who consistently ranks first in your class. Be completely honest: do you genuinely respect their hard work, or do you secretly hope they fail just once so you can feel better about your own mediocrity?",
        "Your parents sacrifice their own luxuries to pay your school fees, yet you complain about the food they cook and the strict rules they set. Isn't that the exact definition of being ungrateful and entitled?",
        "You live in a country with over a billion people where competition is ruthless. If you are not in the top 1%, society will label you average. Are you mentally tough enough to crush the competition, or are you just going to settle for a mediocre life?",
		"'You are just a teenager. Your opinions don't matter yet because you don't pay bills or understand the real world.' Defend your existence against this classic adult insult.",
        "Look at how you waste hours on YouTube and Instagram. Be honest: if you don't achieve your dreams, it won't be because the system is unfair, it will be because you are fundamentally lazy. True or False? Defend your answer.",
        "Some people say that 'mental health breaks' are just excuses invented by a weak generation that cannot handle the pressure their grandparents survived. Are you a weak generation?",
        "In a country of 1.4 billion people, average is invisible. If you don't secure a top rank or get a massive salary, you are a nobody. Does this paralyze you with fear, or ignite your ambition?",
        "You want to be an artist, a writer, or a gamer, but your parents say 'Art is a hobby, Engineering is a career.' What is your logical counter-argument, and do you have the guts to actually follow it through?",
        "Why should anyone hire you in the future? What makes you so special that an AI or someone willing to work 14 hours a day for half your salary shouldn't replace you?",
        "We constantly complain about India's flaws—pollution, corruption, infrastructure. Yet, the moment people get successful, they abandon the country for the US or UK. Are you going to be a hypocrite who runs away too?",
        "Parents constantly remind you of their sacrifices: 'We gave up everything for your education.' Does this make you feel deep gratitude, or like you are just a long-term financial investment trapped by emotional blackmail?",
        "Imagine the person you hate the most becomes wildly successful, rich, and loved by everyone, while you are struggling to make ends meet. How do you mentally process that level of intense jealousy and unfairness?",
        "You claim to have moral principles, but if your boss ordered you to fire a single mother to save the company 1% in profits, and refusing meant you lose your own job, would you do it? Don't give a diplomatic answer.",
		"Society tells you that 'beauty is on the inside', but attractive people clearly get better treatment, jobs, and opportunities. Why are we still lying to teenagers about how the real world works?",
        "If your parents lost all their money tomorrow and couldn't pay for your education, do you have the raw street-smarts to survive and rebuild your life, or are you completely useless without their money?",
        "You hate corruption in politics, but you probably use connections or favors to get things done when it benefits you. Admit it: you don't hate corruption, you just hate that you aren't the one benefiting from it.",
        "Many students claim they have 'social anxiety' just because they lack basic communication skills. Is it a real mental health crisis, or just a lazy excuse to avoid talking to people?",
        "If the school grading system was completely abolished tomorrow, would you still study, or would you stop learning completely because there is no external reward?",
        "We are taught to blindly respect our teachers, but what if your teacher is incompetent, lazy, and biased? Why should you respect someone just because they have a degree?",
        "If you could press a button and permanently erase all social media from existence, you would do it, wouldn't you? Because deep down you know it's destroying your generation's mental health.",
        "You dream of a big house and a luxury car, but you complain when the school gives you an extra assignment. How do you expect to survive the brutal corporate world if you cry over homework?",
        "Is patriotism in India real, or do we only pretend to care about the country during cricket matches and national holidays?",
        "If you knew for an absolute fact that you were going to die in exactly five years, would you still care about your 10th or 12th board exams? Why let society dictate your timeline?",
        "Parents often say 'Do whatever makes you happy.' But if what makes you happy pays only 10,000 rupees a month, they will instantly change their mind. Is parental love truly unconditional?",
        "You want to be independent, but you still need your parents to fill out your forms and solve your problems. Stop acting like a rebel when you are still a dependent child.",
        "The education system forces you to memorize facts you can Google in 3 seconds. Aren't you basically wasting 15 years of your life learning how to be a compliant robot?",
        "If given the power, would you fire the worst teacher in your school today, knowing it would ruin their family's financial stability? Are you that ruthless?",
        "Why do you care so much about what your classmates think of you? In 5 years, you won't even remember 90% of their names. Stop living for peer validation.",
        "People say 'Failure is the stepping stone to success.' But in reality, one major failure in Indian entrance exams can ruin your career trajectory forever. Isn't that quote just toxic positivity?",
        "If you were guaranteed a basic income of 50,000 rupees a month for life without doing any work, would you ever work a single day in your life again?",
        "We talk about equality, but the caste system and religious divisions are still deeply rooted in your generation's mindset. Do you actively fight it, or quietly accept it?",
        "You complain about global warming, but you leave the AC on all night and buy fast fashion. Aren't you part of the problem you claim to hate?",
        "Imagine you reach 40 years old, you have a high-paying job, but you are miserable, stressed, and alone. Will you regret listening to society's definition of 'success'?"
    ]
};